GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJBcm1hbiIsImVtYWlsIjoidGVzdEBnbWFpbC5jb20iLCJpYXQiOjE3MTExODU3MjIsImV4cCI6MTcxMTE4NTczN30.1I5x8RfJro4geykOTHHqgTgbr7I_wsdBx69csjPFJ04


###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Arman",
    "email": "test2@gmail.com",
    "password": "123456",
    "confirmPassword": "123456"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "123456"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout