GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJBcm1hbiIsImVtYWlsIjoidGVzdEBnbWFpbC5jb20iLCJpYXQiOjE3MTEwMDc0MjUsImV4cCI6MTcxMTAwNzQ0NX0.exy4nsbgALE6EwVUK5WftkUSDtRcpn3TqCFqEA4Xryc


###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Arman",
    "email": "test2@gmail.com",
    "password": "123456",
    "confirmPassword": "123456"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "123456"
}